# -*- coding: utf-8 -*-
"""FleetMind AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mo7gC4GMgBlA-l4brakPw3sKjRrhSN4J
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import kagglehub
path = kagglehub.dataset_download("chavindudulaj/vehicle-maintenance-data")
df = pd.read_csv(path+'/vehicle_maintenance_data.csv')
df.head()

df.info()
df.describe()

df.isnull().sum()

df["Need_Maintenance"].value_counts()

# Convert to datetime
df["Last_Service_Date"] = pd.to_datetime(df["Last_Service_Date"])
df["Warranty_Expiry_Date"] = pd.to_datetime(df["Warranty_Expiry_Date"])

# useful numeric features
df["Days_Since_Last_Service"] = (pd.Timestamp.today() - df["Last_Service_Date"]).dt.days
df["Warranty_Days_Left"] = (df["Warranty_Expiry_Date"] - pd.Timestamp.today()).dt.days

# Drop original date columns
df.drop(["Last_Service_Date", "Warranty_Expiry_Date"], axis=1, inplace=True)

X = df.drop("Need_Maintenance", axis=1)
y = df["Need_Maintenance"]
print(X.shape)
print(y.shape)

categorical_cols = X.select_dtypes(include="object").columns
numeric_cols = X.select_dtypes(exclude="object").columns

print("Categorical Columns:")
print(categorical_cols)

print("\nNumeric Columns:")
print(numeric_cols)

# Create preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"
)

# Create full pipeline
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(max_depth=10,random_state=42))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=32
)

print(X_train.shape)
print(X_test.shape)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print("\nClassification Report:\n")
print(classification_report(y_test, pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, pred))